### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by mbenetti** [abhimishra91/insight#2]
Hello! Nice work, it looks very good in the video. Unfortunately, I was not able to make it run. I get this error:

Insight
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback:
File "c:\users\mbene\miniconda3\lib\site-packages\streamlit\script_runner.py", line 324, in _run_script
    exec(code, module.__dict__)
File "C:\Users\mbene\Documents\GitHub\insight-master\insight-master\src_streamlit\NLPfiy.py", line 132, in <module>
    main()
File "C:\Users\mbene\Documents\GitHub\insight-master\insight-master\src_streamlit\NLPfiy.py", line 118, in main
    model_details = apicall.model_list(service=service)
File "C:\Users\mbene\Documents\GitHub\insight-master\insight-master\src_streamlit\NLPfiy.py", line 24, in model_list
    return json.loads(models.text)
File "c:\users\mbene\miniconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
File "c:\users\mbene\miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "c:\users\mbene\miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

In any of the service I get the same message (only change the URL endpoint)

.- I already add the sreamlit to the docker network
.- I already down and up the firewall
.- Create an exception in the firewall
.- Update docker and docker-compose
.- In Linux Ubuntu and Windows 10 is the same error
.- Installed the requirements.txt
.- I can't access the localhost:8000/docs.
.- And l already tried docker run the Dockerfile inside streamlit, and add it to the network

no success so far.

I would appreciate your help. Thank you!

Mauro

**Comment by mbenetti** [comment]
I forgot to mention, I can't access the localhost:8000/docs. 
And l already tried docker run the Dockerfile inside streamlit, and add it to the network

no success so far.

**Comment by abhimishra91** [comment]
Hi @mbenetti , thanks for trying the application. Please can you confirm if you tired to run the streamlit app, using the `Dockerfile` or as per the instruction given in the readme (to use the `streamlit run` command)

For now use the `streamlit run` command. Docker is still in works.

**Comment by mbenetti** [comment]
Hello!

I tried both options.

The interesting thing is I tried in another computer without anaconda and the error is not there anymore. The front end is working but I can’t build with docker-compose the services.

I’ll try a fresh installation of python on my last computer. The strange thing is the docker front end should not have problems with the Jsonlib.

Thank you for your fast response.

Mauro

Sent from my iPhone

On 24. Aug 2020, at 14:06, Abhishek Kumar Mishra <notifications@github.com> wrote:

﻿

Hi @mbenetti<https://github.com/mbenetti> , thanks for trying the application. Please can you confirm if you tired to run the streamlit app, using the Dockerfile or as per the instruction given in the readme (to use the streamlit run command)

For now use the streamlit run command. Docker is still in works.

**Comment by abhimishra91** [comment]
That is strange indeed. I have successfully tested docker-compose with the streamlit app on a Linux Mint machine with anaconda installed.  

The docker for streamlit is still in works. As the whole docker thing is new to me :) So a bit slow on the uptake.

**Comment by mbenetti** [comment]
No problem, you are doing a great job. I’m new in fastapi and streamlit :D

Best regards

Mauro

Sent from my iPhone

On 24. Aug 2020, at 14:35, Abhishek Kumar Mishra <notifications@github.com> wrote:

﻿

That is strange indeed. I have successfully tested docker-compose with the streamlit app on a Linux Mint machine with anaconda installed.

The docker for streamlit is still in works. As the whole docker thing is new to me :) So a bit slow on the uptake.

**Comment by mbenetti** [comment]
Is not working. I tried a new installation of python in a Ubuntu 20 but I get the same JsonDecoErroe. I think maybe there’s a missing dependency in the file requirements.txt?

Best regards

Mauro

Sent from my iPhone

On 24. Aug 2020, at 14:35, Abhishek Kumar Mishra <notifications@github.com> wrote:

﻿

That is strange indeed. I have successfully tested docker-compose with the streamlit app on a Linux Mint machine with anaconda installed.

The docker for streamlit is still in works. As the whole docker thing is new to me :) So a bit slow on the uptake.

**Comment by abhimishra91** [comment]
So as of now, your getting this error for the streamlit part? 

To double check the backend is getting deployed and running as expected? Or am i missing anything? The back-end can be tested via postman if the api is working as expected or not.

**Comment by mbenetti** [comment]
Front end is running but when I try to access any of the services I get the error. Back end, I can see the containers in Portainer but I have no access to fastapi, no access to localhost:8000/docs. I think the problem is in my backend, I don’t know how test it.

Mauro A. Benetti

**Comment by abhimishra91** [comment]
Hi @mbenetti , 

For the backend `fastapi` aspect, you can test the deployed solution with postman. 

Also the fastapi documentation is available here as per the latest code that i have posted:

News Classification: http://localhost:8080/api/v1/classification/docs
Sentiment Analysis: http://localhost:8080/api/v1/sentiment/docs
NER: http://localhost:8080/api/v1/ner/docs
Summarization: http://localhost:8080/api/v1/summary/docs

**Comment by mbenetti** [comment]
I have access to the api 
![image](https://user-images.githubusercontent.com/27162948/91057719-e1862780-e627-11ea-921b-a24c0e01819a.png)

![image](https://user-images.githubusercontent.com/27162948/91057879-15614d00-e628-11ea-8c98-88598d105809.png)
I have access to the main page

![image](https://user-images.githubusercontent.com/27162948/91057935-29a54a00-e628-11ea-9734-b3a7faa08e69.png)
The problem I think is between front end and nginx

**Comment by abhimishra91** [comment]
Thanks for the screenshots. I will do some more testing at my end with a different machine.

But if the backend is working, (I am guessing from the docs page being up). This should be easier to fix.

**Comment by abhimishra91** [comment]
I have pushed an update to the streamlit code, this should fix the issue. Let me know if it is otherwise. The application should now render the page and give you the list of models in the drop down.

**Comment by mbenetti** [comment]
perfect ! what was it?

**Comment by mbenetti** [comment]
I have access to all the services except Summarization.

**Comment by abhimishra91** [comment]
Hahaha, this is really sloppy work from me. Another update, summary should also work now. 

I totally missed to push the updates to github remote for the url changes and service changes for the streamlit app, on back of changes i made in the back-end architecture today. 

Please do note, the predictions will not run as the model.bin files got removed (I ran out of my lfs allocation). But you can use the [transformer-tutorials](https://github.com/abhimishra91/transformers-tutorials) to generate the same models.

**Comment by abhimishra91** [comment]
I have uploaded the model on google drive temporarily. You can download the files and add them to the respective model files. 

https://drive.google.com/drive/folders/1Lc7kvfNnMRgA7tkPR5zaSAoSjC2sCudI?usp=sharing

I will update the code base once my lfs allocation gets free.

**Comment by mbenetti** [comment]
Thank you! I have a lot to learn and try with this project.

**Comment by abhimishra91** [comment]
Cheers! On the same boat. Learning as i work on these projects. I will close this issue for now. 
But please do open any new issues if you have questions or run into errors.
