### ISSUE TITLE
No model.bin in the repo

### ISSUE THREAD

**Issue by AnilB87** [abhimishra91/insight#3]
Hi Abhi Mishra

Amazing work. Really like the idea of building NLP services. I'm highly interested in augmenting the models with custom features for sentiment analysis. Is it possible for you to upload the model files (pytorch_model.bin) to try different NLP pipelines for sentiment analysis?

**Comment by abhimishra91** [comment]
Hi @AnilB87 , thanks for the feedback. 

The model files got removed as i exceeded my allocation of lfs. I have uploaded the model files on google drive: https://drive.google.com/drive/folders/1Lc7kvfNnMRgA7tkPR5zaSAoSjC2sCudI?usp=sharing

You can download them from here and add them to the respective folders for inference. Will update the code base once my allocation gets refreshed in next 6 days.

For leveraging additional models you can use the [transformer-tutorials](https://github.com/abhimishra91/transformers-tutorials) and create your own model and upload the files as recommended in the readme.

**Comment by AnilB87** [comment]
@abhimishra91 thanks for sharing the model files. Sure will follow the tutorials to create new models and upload them.
