### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mbenetti** [abhimishra91/insight#4]
Hello Abhishek 
I try today with the latest changes but still is not working for me. Now I get "Internal Server Error" using FastAPI Swagger UI (see picture)

![image](https://user-images.githubusercontent.com/27162948/91198589-05676d00-e6fd-11ea-9b41-bbc7efa58d46.png)

If I request a GET info, I get the name and the description of the model (see next picture)

![image](https://user-images.githubusercontent.com/27162948/91198363-c0dbd180-e6fc-11ea-9880-713762e3198f.png)

The front end present the same Json decoder error as yesterday.

![image](https://user-images.githubusercontent.com/27162948/91198901-760e8980-e6fd-11ea-812f-35421636bc16.png)

I tried in windows and linux again.

**Comment by abhimishra91** [comment]
@mbenetti , thanks for raising this. Let me have a look and get back to you.

**Comment by abhimishra91** [comment]
Hi @mbenetti, i tested a fresh install and setup on Linux machine and it looks to be working for me. 
Just wanted to check, have you downloaded the model.bin files from the google drive link and saved them in the correct location. For each service? 

As far as i can see from the screenshots, the `/info` path is working fine. But your getting a server error in `/predict` path. This might be due to the absence of `model.bin` files. As they do not come with the code base (my gitlfs quota is completely used up)

**Comment by asehmi** [comment]
The same thing happened to me as @mbenetti, the first time I hit the end point as additional files were being dynamically downloaded by the transformer libs. Once the files had downloaded and I hit the end point again, it worked fine.

I can't get the NER service to work as there are quite a few missing parts that Spacy is looking for.

I can see all the error messages when I omit the -d flag for docker-compose.

@abhimishra91 this is an interesting project and I hope to learn a bit about transformers from it. Thanks.

In my own public repos, I've shared some streamlit work that I've done. Feel free to grab it!

**Comment by abhimishra91** [comment]
@asehmi , thanks for chipping in. Yes, it downloads the standard weights of the transformers network from s3 the first time it executes. And then it does the inference. Being said that it never failed while i was testing...It only delayed the response time. 
If you want to know more about transformers, you can have a look at [transfomers-tutorials](https://github.com/abhimishra91/transformers-tutorials)
I will definitely i have look at your repo thanks! 

@mbenetti, please can you confirm if your still getting the error?

**Comment by mbenetti** [comment]
@abhimishra91, I downloaded the models and put in the correspondent folders. And yes, I still have the same problem.

**Comment by mbenetti** [comment]
Is working now! It was a dependency as I suspected. The problem is I don't know which one was.

Working with Streamlit I installed:

gensim 3.8.3 and this software depends on NumPy and Scipy. 

But because I tried to make it work outside the container so I also later installed:

conda install -c conda-forge beautifulsoup4
conda install -c conda-forge textblob
python -m textblob.download_corpora
pip install sumy
pip install smart-open
pip install urllib3   
pip install urlopen       
conda install -c anaconda nltk   
python -m nltk.downloader all       

Update:
Classification with DistilBERT (working)
Named Entity Recognition with spaCy (not working) (same error JSONDecodeError)
Sentiment Analysis ( not working ) (TypeError: string indices must be integers)
Summarization T5 (not working) (same error JSONDecodeError)

**Comment by abhimishra91** [comment]
wah! that is good news! I really need to work on the docker for streamlit so that users in the future do not have this issue.

Thanks for working through this.

**Comment by mbenetti** [comment]
sorry @abhimishra91 
Update:
Classification with DistilBERT (working)
Named Entity Recognition with spaCy (not working) (same error JSONDecodeError)
Sentiment Analysis ( not working ) (TypeError: string indices must be integers)
Summarization T5 (not working) (same error JSONDecodeError)

I have a Streamlit file running similar model without Containers and API. Some how the API is not running properly

**Comment by asehmi** [comment]
> wah! that is good news! I really need to work on the docker for streamlit so that users in the future do not have this issue.
> 
> Thanks for working through this.

Your streamlit docker is fine. Just need to run these commands:

  ```console
  $ docker build src_streamlit
  $ docker images
  $ docker run -p 127.0.0.1:8501:8501 <image-id>
  ```

Am sure you can give the image a pretty name and run it with that, instead of the `image-id`.

Open `http://localhost:8501` in a browser window

By the way, I've built all of this on Windows 10, Docker for Windows with WSL 2 support, though I'm not using WSL. No problems so far as you aren't running any bash scripts or changing any file props. :-)
